mosquitto:
  container_name: mosquitto
  image: eclipse-mosquitto
  restart: unless-stopped
  user: "1883"
  ports:
    - "1883:1883"
  volumes:
    - ./volumes/mosquitto/data:/mosquitto/data
    - ./volumes/mosquitto/log:/mosquitto/log
    - ./volumes/mosquitto/pwfile:/mosquitto/pwfile
    - ./services/mosquitto:/mosquitto/config:ro
  networks:
    - iotstack_nw
