  gitea:
    container_name: gitea
    image: "kunde21/gitea-arm:latest"
    restart: unless-stopped
    ports:
      - "7920:3000/tcp"
      - "2222:22/tcp"
    environment:
      - USER_UID=1000
      - USER_GID=1000
    env_file:
      - ./services/gitea/gitea.env
    volumes:
      - ./volumes/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
