zigbee2mqtt:
  container_name: zigbee2mqtt
  image: koenkk/zigbee2mqtt
  volumes:
    - ./volumes/zigbee2mqtt/data:/app/data
  devices:
    - /dev/ttyAMA0:/dev/ttyACM0
    #- /dev/ttyUSB0:/dev/ttyACM0 # Electrolama zig-a-zig-ah! (zzh!) maybe other as well
  restart: unless-stopped
  network_mode: host
